trigger:
- main

pool:
  name: default

variables:
  DOCKERHUB_REPOSITORY: 'brahmieya/stage'
  KUBECONFIG: '/home/vsts/.kube/config'

stages:
  - stage: build_and_push
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: build_and_push
        displayName: 'Build and Push'
        steps:
          - script: |
              docker build -t $(DOCKERHUB_REPOSITORY):$(Build.BuildId) .
            displayName: 'Build Docker Image'

          - task: Docker@2
            displayName: 'Push Docker Image to Docker Hub'
            inputs:
              containerRegistry: 'dockerhub'
              repository: '$(DOCKERHUB_REPOSITORY)'
              command: 'push'
              tags: '$(Build.BuildId)'

  - stage: deploy_to_k8s
    displayName: 'Deploy to Kubernetes'
    jobs:
      - job: deploy
        displayName: 'Deploy'
        steps:
          - task: Kubectl@1
            displayName: 'Apply Kubernetes Configuration'
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'connectioncluster'
              manifests: 'k8s/appfront.yml'
