# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: 
  displayName: Build image
  jobs:
  - job: test
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SnykSecurityScan@1
      displayName: Snyk Security Scan
      inputs:
        serviceConnectionEndpoint: 'snyktest'
        testType: 'code'
        failOnIssues: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          v1
    
