trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubConnection: 'DockerHubConnection'
  imageName: 'brahmieya/votre-image:latest'  # Specify the image name with tag

steps:
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyktest'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'test0'
    

