trigger:
  branches:
    include:
      - master

pool:
  name: default

stages:
  - stage: build_docker_image
    jobs:
      - job: build_image
        displayName: 'Build Docker Image'
        steps:
          - script: |
              sudo usermod -aG docker $(whoami)
              sudo systemctl restart docker
              newgrp docker
            displayName: 'Add user to docker group and restart Docker'

          - script: |
              docker build -t myimage:latest .
            displayName: 'Build Docker Image'