pr: none

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker pull ghcr.io/aquasecurity/trivy:latest
    docker pull mysql:latest
    docker run --rm ghcr.io/aquasecurity/trivy:latest image mysql:latest --format html > $(System.DefaultWorkingDirectory)/résultat.html
  displayName: 'Scan MySQL image with Trivy'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/résultat.html'
    artifactName: 'trivy-report'
    publishLocation: 'pipeline'
  displayName: 'Publish Trivy Report'

