pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker pull aquasec/trivy:latest
    docker pull mysql:latest
    docker run --rm aquasec/trivy:latest image mysql:latest > $(System.DefaultWorkingDirectory)/résultat.txt
  displayName: 'Scan MySQL image with Trivy'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/résultat.txt'
    artifactName: 'trivy-report'
    publishLocation: 'pipeline'
  displayName: 'Publish Trivy Report'
