trigger:
  branches:
    include:
      - master

pool:
  name: default

stages:
  - stage: testsnyk
    jobs:
      - job: snykScan
        steps:
          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'snyktest'
              testType: 'code'
              failOnIssues: false

  - stage: build
    displayName: Build
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - task: Npm@1
            displayName: 'Install Angular CLI'
            inputs:
              command: 'custom'
              customCommand: 'install -g @angular/cli@14.1.0'
              

          - task: Npm@1
            displayName: 'Install npm packages'
            inputs:
              command: 'install'
              
              verbose: true

          - task: CmdLine@2
            displayName: 'Build Angular app'
            inputs:
              script: 'ng build --prod'
