trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubConnection: 'DockerHubConnection'
  imageName: 'brahmieya/votre-image:latest'  # Specify the image name with tag

steps:
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snyktest'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'test0'
    
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'

- script: |
    docker build -t $(imageName) .
    docker login -u $(dockerHubConnection.username) -p $(dockerHubConnection.password)
    docker push $(imageName)
  displayName: 'Build and push Docker image'
