trigger:
- main

pool:
  name: default

variables:
  DOCKERHUB_REPOSITORY: 'brahmieya/stage'  
  KUBECONFIG: '/home/vsts/.kube/config'

stages:
  - stage: build_and_push
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: build_and_push
        displayName: 'Build and Push'
        steps:
          - script: |
              docker build -t $(DOCKERHUB_REPOSITORY):$(Build.BuildId) .
            displayName: 'Build Docker Image'

          - task: Docker@2
            displayName: 'Push Docker Image to Docker Hub'
            inputs:
              containerRegistry: 'dockerhub'
              repository: '$(DOCKERHUB_REPOSITORY)'
              command: 'push'
              tags: '$(Build.BuildId)'

  - stage: deploy_to_k8s
    displayName: 'Deploy to Kubernetes'
    jobs:
      - job: deploy
        displayName: 'Deploy'
        steps:
          - script: |
              az account set --subscription 3ef060fd-73bf-4a86-b880-398d0e68c239
              az aks get-credentials --resource-group NetworkWatcherRG --name clusterstage --overwrite-existing
            displayName: 'Get AKS Credentials'
        
          - task: Kubectl@1
            displayName: 'Apply Kubernetes Configuration'
            inputs:
              kubernetesServiceEndpoint: 'connectioncluster'
              command: 'apply'
              arguments: '-f k8s/appfront.yml'
