trigger:
  branches:
    include:
      - master

pool:
  name: default

stages:
  - stage: testsnyk
    jobs:
      - job: snykScan
        steps:
          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'snyktest'
              testType: 'code'
              failOnIssues: false


  - stage: build_docker_image
    jobs:
      - job: build_image
        displayName: 'Build Docker Image'
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          
          - script: |
              # Commande Docker build
              docker build -t myimage:latest .
            displayName: 'Build Docker Image'
