trigger:
  branches:
    include:
      - master

pool:
  name: default

stages:
  - stage: testsnyk
    jobs:
      - job: snykScan
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y git
            displayName: 'Install Git'

          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'snyktest'
              testType: 'code'
              failOnIssues: false
