trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


steps:
    - task: SnykSecurityScan@1
      displayName: Snyk Security Scan
      inputs:
        serviceConnectionEndpoint: 'snyktest'
        testType: 'code'
        failOnIssues: false
