trigger:

  branches:
    include:
      - master

pool:
  name: default

stages:
  - stage: analyse_sonarcloud
    displayName: 'Analyze with SonarCloud'
    jobs:
      - job: sonarcloud_analysis
        displayName: 'SonarCloud Analysis'
        steps:
         - task: SonarCloudPrepare@2
           inputs:
              SonarCloud: 'sonarcloud'
              organization: 'projetdevsecops'
              scannerMode: 'MSBuild'
              projectKey: 'projetdevsecops'
              projectName: 'projetdevsecops'