pr: none # for test  for manual run only

pool:
  name: default
stages:
  - stage: analyse_sonarcloud
    displayName: 'Analyse with SonarCloud'
    jobs:
      - job: sonarcloud_analysis
        displayName: 'SonarCloud Analysis'
        steps:
          - checkout: self
            fetchDepth: 0

          - task: SonarCloudPrepare@2
            inputs:
              SonarCloud: 'sonarcloud'
              organization: 'projetdevsecops'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'hadillabidi_DevSecOps'
              cliProjectName: 'DevSecOps'
              cliSources: '.'

          # Example: Build and test your application here before SonarCloud analysis

      - job: build_app
        displayName: 'Build Application'
        dependsOn: sonarcloud_analysis
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js for frontend'

          # Verify Node.js and npm installation
          - script: |
              node -v
              npm -v
            displayName: 'Verify Node.js and npm version'

          # Clean npm cache
          - script: npm cache clean --force
            displayName: 'Clean npm cache'

          # Install project dependencies
          - script: npm install --legacy-peer-deps
            displayName: 'Install project dependencies'

          # Install Angular CLI globally
          - script: npm install -g @angular/cli
            displayName: 'Install Angular CLI globally'

          # Build the application
          - script: npm run build
            displayName: 'Build Application'

  - stage: publish_sonarqube
    displayName: 'Publish to SonarQube'
    jobs:
      - job: publish_sonarqube
        displayName: 'Publish Analysis to SonarQube'
        steps:
          - task: SonarCloudAnalyze@2
            inputs:
             jdkversion: 'JAVA_HOME_17_X64'
          - task: SonarQubePublish@6
            inputs:
              pollingTimeoutSec: '300'