
trigger:
  branches:
    include:
      - master

pool:
  name: default
variables:
  DOCKERHUB_REPOSITORY: 'brahmieya/stage'  
stages:
  - stage: build_and_push
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: build_and_push
        displayName: 'Build and Push'
        steps:
          - script: |
              docker build -t $(DOCKERHUB_REPOSITORY):$(Build.BuildId) .
            displayName: 'Build Docker Image'

          - task: Docker@2
            displayName: 'Push Docker Image to Docker Hub'
            inputs:
              containerRegistry: 'dockerhub'
              repository: '$(DOCKERHUB_REPOSITORY)'
              command: 'push'
              tags: '$(Build.BuildId)'
              Dockerfile: '**/Dockerfile' 
