# Remove the trigger section for manual run only
# trigger:
# - main

# Add pr section to prevent PR triggers
pr: none

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker pull aquasec/trivy:latest
    docker pull mysql:latest
    docker run  aquasec/trivy:latest image --format html --output /root/.cache/trivy-report.html mysql:latest
  displayName: 'Scan MySQL image with Trivy'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/trivy-report.html'
    artifactName: 'trivy-report'
    publishLocation: 'pipeline'
  displayName: 'Publish Trivy Report'
